contact/apps/author/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', home),
    url(r'^register/', Register.as_view(), name='register'),
    url(r'^user_setting/$', Settings.as_view(), name='settings_user'),
]

contact/apps/core/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^add/$', add, name='add'),
    url(r'^update/$', update, name='update'),
    url(r'^data_import/$', data_import, name='data_import'),
    url(r'^update/get_value/$', get_value, name='get_value'),
    url(r'^update/delete_row/$', delete_row, name='delete_row'),
    url(r'^send_contacts/$', send_contacts, name='send_contacts'),
    url(r'^list_of_contacts/$', ajax_list_of_contacts, name='list_of_contacts'),
]

contact/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('contact.apps.author.urls', namespace='author')),
    url(r'^', include('contact.apps.core.urls', namespace='core')),
]

contact/apps/templates/index.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href = "{% static 'css/modal.css' %}" />
{% endblock %}

{% block nav_sidebar %}

<div class="main-sidebar">
    <!-- Inner sidebar -->
        <div class="sidebar">
        <!-- user panel (Optional) -->
            <div class="user-panel">
                <div class="pull-left info">
                    <p></p>
                      <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div><!-- /.user-panel -->
        <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="active"><a href="{% url 'author:settings_user' %}"><span>SETTINGS</span></a><</li>
            </ul><!-- /.sidebar-menu -->
        </div><!-- /.sidebar -->
</div><!-- /.main-sidebar -->

{% endblock %}

{% block content %}

{#    --- BUTTONS for navigation --- #}
<div class="box box-solid box-default">
    <div class="inline">
        <button type="submit" class="btn btn-success my_button" id="my_modal_runner">ADD new contact</button>
        <button type="submit" class="btn btn-success my_button" id="button_for_api">Send to GETVERO your contacts</button>
        <button type="submit" class="btn btn-success my_button" id="button_for_import">Import DATA from CSV-file</button>
    </div>
</div>

{#        --- MODAL WINDOW for IMPORT ---       #}
<form name="form_import" id="form_for_import" action="{% url 'core:data_import' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div class="modal fade" id="myModal_import" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel_update">IMPORT</h4>
                </div>
                    <div class="modal-body"><!-- -->
                         <h4>Choose your DATA csf-file ...</h4>
                        <div>
                            <input type="file" name="data_input_file" id="input_file">
                        </div>
                    </div>
                <div class="modal-footer"><!-- -->
                    <button type="submit" class="btn btn-success" id="button_for_confirmation_to_import">YES</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary hidden" data-dismiss="modal" id="btn-dismiss_import">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>


{#        --- MODAL WINDOW for SEND CONTACTS ---       #}
<form id="form_for_api" action="{% url 'core:send_contacts' %}"> {% csrf_token %}
    <div class="modal fade" id="myModal_send" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel_update">SEND</h4>
                </div>
                    <div class="modal-body"><!-- -->
                         <h4>You are sure that you want to send your data to GETVERO?</h4>
                    </div>
                <div class="modal-footer"><!-- -->
                    <button type="submit" class="btn btn-success" id="button_for_confirmation_to_send">YES</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary hidden" data-dismiss="modal" id="btn-dismiss_send">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</form>


{#        --- MODAL WINDOW TO ADD ---       #}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form_add" action="{% url 'core:add' %}"> {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">ADD new contact</h4>
                </div>
                <div class="modal-body"><!-- -->
                    <div class="modal_inline">
{#                        <label>FIRST NAME:</label>#}
                        <input type="text" class="form-control add_input" name="number_first_name" id="number_first_name" placeholder="First name">
                    </div>
                    <div class="modal_inline">
{#                        <label>LAST NAME:</label>#}
                        <input type="text" class="form-control add_input" name="number_last_name" id="number_last_name" placeholder="Last name">
                    </div>
                    <div class="modal_inline">
{#                        <label>COUNTRY:</label>#}
                        <select id="country_select" class="form-control add_input">
                            {% for country in countries_list %}
                                <option>{{ country.country_name }},&nbsp;{{ country.country_code }}</option>
                            {% endfor %}
                        </select>
{#                        <input type="text" class="form-control add_input" name="number_country" id="number_country" placeholder="Country">#}
                    </div>
                    <div class="modal_inline">
{#                        <label>TOWN:</label>#}
                        <input type="text" class="form-control add_input" name="number_town" id="number_town" placeholder="Town">
                    </div>
                    <div class="modal_inline">
{#                        <label>PHONE:</label>#}
                        <input type="number" class="form-control add_input" name="number_phone" id="number_phone" placeholder="Phone">
                    </div>
                    <div class="modal_inline">
{#                        <label>EMAIL:</label>#}
                        <input type="text" class="form-control add_input" name="number_email" id="number_email" placeholder="Email">
                    </div>
                </div>
                <div class="modal-footer"><!-- -->
                    <button type="submit" class="btn btn-success btn-add" id="button_add"
                        data-id = "{{ user.id }}">
                        ADD
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary hidden" data-dismiss="modal" id="btn-add_dismiss">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>


{#        --- MODAL WINDOW TO UPDATE AND DELETE ---       #}
<div class="modal fade" id="myModal_update" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="form_update" action="{% url 'core:update' %}"> {% csrf_token %}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel_update">UPDATE contact</h4>
                </div>
                <div class="modal-body"><!-- -->
                        <div class="modal_inline">
                            <label>FIRST NAME:</label>
                            <input type="text" class="form-control add_input" name="number_first_name" id="number_first_name_update">
                        </div>
                        <div class="modal_inline">
                            <label>LAST NAME:</label>
                            <input type="text" class="form-control add_input" name="number_last_name" id="number_last_name_update">
                        </div>
                        <div class="modal_inline">
                            <label>COUNTRY:</label>
                            <input type="text" class="form-control add_input" name="number_country" id="number_country_update">
                        </div>
                        <div class="modal_inline">
                            <label>TOWN:</label>
                            <input type="text" class="form-control add_input" name="number_town" id="number_town_update">
                        </div>
                        <div class="modal_inline">
                            <label>PHONE:</label>
                            <input type="number" class="form-control add_input" name="number_phone" id="number_phone_update">
                        </div>
                        <div class="modal_inline">
                            <label>EMAIL:</label>
                            <input type="text" class="form-control add_input" name="number_email" id="number_email_update">
                        </div>
                </div>
                <div class="modal-footer"><!-- -->
                    <button type="button" class="btn btn-success" id="button_delete">
                        DELETE
                    </button>
                    <button type="submit" class="btn btn-success">
                        UPDATE
                    </button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary hidden" data-dismiss="modal" id="btn-dismiss_update">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>


{#          --- DataTable ---        #}
<div class="box">
    <div class="box-header">
        <div class="box-body">
            <table id="table_of_contacts" class="dataTables_wrapper form-inline dt-bootstrap" cellspacing="0" width="100%">
{#                class="table table-striped table-bordered"                #}
                <thead>
                    <tr>
                        <th>Num</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Country</th>
                        <th>Town</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Birthday</th>
                        <th>Created</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Num</th>
                        <th>First name</th>
                        <th>Last name</th>
                        <th>Country</th>
                        <th>Town</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Birthday</th>
                        <th>Created</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>


    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "js/server_side.js" %}"></script>
    <script type="text/javascript" src="{% static "js/add_cont.js" %}"></script>
    <script type="text/javascript" src="{% static "js/update_cont.js" %}"></script>
    <script type="text/javascript" src="{% static "js/send_cont.js" %}"></script>
    <script type="text/javascript" src="{% static "js/import_data.js" %}"></script>

{% endblock %}

{% block extra_foot %}

    <link rel="stylesheet" href = "{% static "css/bootstrap.min.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery.dataTables.min.css" %}">
    <script type="text/javascript" src="{% static "js/datatables.min.js" %}"></script>

{% endblock %}